import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import { cookies } from "next/headers";
import "@fontsource-variable/playfair-display";
import "@fontsource-variable/figtree";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getProfile() {
  const accessToken = cookies().get("accesstoken");
  const userName = cookies().get("username");
  let logins = cookies().get("logins");

  if (accessToken && userName) {
    const response = await fetch(
      `https://v2.api.noroff.dev/holidaze/profiles/${userName.value}`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${accessToken.value}`,
          "X-Noroff-API-Key": "74f572d2-19b2-4919-8edd-45508b626fed",
        },
      }
    );
    const data = await response.json();

    data.data.logins = logins?.value ?? 0;

    return data.data;
  }
  return undefined;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await getProfile();

  return (
    <html lang="en">
      <body>
        <div className="container mx-auto">
          <Layout userProfile={profile}>{children}</Layout>
        </div>
      </body>
    </html>
  );
}
